### ISSUE TITLE
Local GraphRAG?

### ISSUE THREAD

**Issue by lukajandric** [freistli/AdvancedRAG_SVC#1]
Would be great if it could utiliize local GraphRAG so it does not have to depend on external APIs for it.

Kudos to Microsoft for open sourcing it, but 30+ Azure resource Kubernetes monster just to wrap APIs around single python lib one can use directly is bit crazy (of cour$e not to them).

E.g. https://github.com/severian42/GraphRAG-Local-UI

**Comment by freistli** [comment]
Fully agree, a local agile instance can be easier to experiment GraphRAG, I plan to either write self local GraphRAG interface or leverage the project you shared as next main update..
